name: google_sheets_orm
description: "ORM for Google Sheets"
version: 1.0.0
homepage: https://github.com/senuntech/google_sheets_orm

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  googleapis: ^13.2.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: